Global:
  device: gpu
  epoch_num: 150
  print_batch_step: 10
  output_dir: ./output/rec/svtrv2_fourier_nano_slim/
  log_smooth_window: 20
  save_epoch_step: [0, 10]
  eval_epoch_step: [0, 10]
  eval_batch_step: [0, 999999999]
  cal_metric_during_train: True
  pretrained_model: /content/OpenOCR/output/rec/u14m_filter/svtrv2_tiny_rctc/best.pth
  checkpoints:
  use_tensorboard: false
  use_wandb: True
  wandb_project: OpenOCR_SVTR_PhD
  run_name: svtrv2_fourier_nano_slim
  character_dict_path: &character_dict_path ./tools/utils/license_plate_vn_dict.txt
  max_text_length: &max_text_length 25
  use_space_char: &use_space_char False
  use_amp: True

Optimizer:
  name: AdamW
  lr: 0.001
  weight_decay: 0.05
  filter_bias_and_bn: True

LRScheduler:
  name: OneCycleLR
  warmup_epoch: 1.5
  cycle_momentum: False

Architecture:
  model_type: rec
  algorithm: SVTRv2
  Transform:
  Encoder:
    name: SVTRv2LNConvTwo33
    use_pos_embed: False
    dims: [48, 96, 192]
    depths: [3, 6, 3]
    num_heads: [3, 6, 12]
    # Replace all Global Attention with Fourier
    mixer: [['Conv','Conv','Fourier'],['Conv','Conv','Conv','Fourier','Fourier','Fourier'],['Fourier1D','Fourier1D','Fourier1D']]
    local_k: [[5, 5], [5, 5], [-1, -1]]
    sub_k: [[1, 1], [2, 1], [-1, -1]]
    last_stage: false
    feat2d: True
  Decoder:
    name: RCTCDecoder

Loss:
  name: CTCLoss
  zero_infinity: True

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  is_filter: True

Train:
  dataset:
    name: RatioDataSetTVResize
    ds_width: True
    padding: False
    data_dir_list: ['/content/ocr-license-plate-lmdb-dataset/train']
    transforms:
      - DecodeImagePIL:
          img_mode: RGB
      - PARSeqAugPIL:
      - CTCLabelEncode:
          character_dict_path: *character_dict_path
          max_text_length: *max_text_length
          use_space_char: *use_space_char
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    batch_size_per_card: 128
    shuffle: True
    drop_last: True
    num_workers: 8
    max_ratio: 4
  sampler:
    name: RatioSampler
    is_training: True
    first_bs: 128
    divided_factor: [4, 16]
    scales: [[128, 32]]

Eval:
  dataset:
    name: RatioDataSetTVResize
    ds_width: True
    padding: False
    data_dir_list: ['/content/ocr-license-plate-lmdb-dataset/val']
    transforms:
      - DecodeImagePIL:
          img_mode: RGB
      - CTCLabelEncode:
          character_dict_path: *character_dict_path
          max_text_length: *max_text_length
          use_space_char: *use_space_char
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    batch_size_per_card: 128
    shuffle: False
    drop_last: False
    num_workers: 4
    max_ratio: 4
  sampler:
    name: RatioSampler
    is_training: False
    first_bs: 128
    divided_factor: [4, 16]
    scales: [[128, 32]]
